# version 1.1.0
mirror:
    script:
        - git config --global push.default simple
        - git config --global push.followTags true
        - git checkout -f ${CI_COMMIT_REF_NAME}
        - git pull origin ${CI_COMMIT_REF_NAME}
        - git push -q https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git --all


